[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
# members
kernel.workspace = true
shared.workspace = true
registry.workspace = true
# external
axum.workspace = true
derive-new.workspace = true
serde.workspace = true
anyhow.workspace = true
uuid.workspace = true
thiserror.workspace = true
